version: '3.4'

services:
  sportserver:
    image: sportserver
    container_name: sportserver
    build:
      context: .
      dockerfile: SportServer/Dockerfile
    depends_on:
      - mysql
    networks:
      - main
    environment:
      - SPORT_CONNECTION=Server=mysql;Port=3306;Database=sportapp;Uid=root;Pwd=toor;
      - ASPNETCORE_URLS=http://+:5000
      - ISSUER=SportApp
      - SECRET_KEY=qwuyteqtuwyytudgiuygioydfigoy123gyfdgydfsgygyfdsgy312guydowfsghilydfko
      - AUDIENCE=Administrator

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    networks:
      - main
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: sportapp
    volumes:
      - db:/var/lib/mysql
  
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - 80:80
      - 443:443
    networks:
      - main
    volumes:
      - ./Caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  db:
  caddy_data:
  caddy_config:

networks:
  main:
    external: true
  
